# Uncomment the next line to define a global platform for your project
#platform :ios, '13.3'

target 'MapApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FloatingPanel'
  pod 'Google-Mobile-Ads-SDK'
  #pod 'RealmSwift'

  # Pods for MapApp

  target 'MapAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapAppUITests' do
    # Pods for testing
  end

end

target 'MapAppWatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapAppWatch

end

target 'MapAppWatch Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapAppWatch Extension

end
